<?php include('perch/runtime.php'); ?> <!DOCTYPE html> <html lang="en"> <head> <meta charset="UTF-8"> <meta name="viewport" content="width=device-widthinitial-scale=1"> <link rel="dns-prefetch" href="https://fonts.googleapis.com"> <link rel="dns-prefetch" href="https://spin3.ianhobbsmedia.com"> <link rel="stylesheet" href="/css/simple5colGrid.css"> <link rel="shortcut icon" href="/images/icon/favicon.ico" type="image/x-icon"> <meta name="description" content="ian hobbs media site. Ian Hobbs is an artist - media artist working in fine arts and design"> <meta name="keywords" content="ian hobbs, media, code, strategy, artist, design, photography, interactive, media photographer sydney australia"> <link rel="author" href="https://plus.google.com/117732578082555700649/about"> <title>ian hobbs works</title> </head> <body> <div class="container" x-data="{ isOpen: false}"> <div class="transformer" x-bind:class="{'is-open': isOpen }"> <nav class="off-canvas"> <div class="offside-wrap w-60"> <h4 class="pad-top-500 md:pad-top-800 lg:pad-top-800">menu</h4> </div> <div class="offside-wrap"> <nav class="offside"> <?php perch_pages_navigation(array(
                     'template' => 'item-vert.html',
                     ));
                   ?> </nav> </div> </nav> <div class="content"> <div class="fiveCol"> <nav class="main gap-top-600 gap-bottom-400"> <p class="ttu lh-copy f6 b sans-serif tl center indexical"><?php perch_content('Little Header'); ?></p> </nav> <div class="burger gap-top-600 gap-bottom-400"> <button class="hamburger hamburger--slider" type="button" x-on:click="isOpen = !isOpen" @click.outside="isOpen = false" @keyup.escape="isOpen = false" :class="{ 'is-active': isOpen }"> <div class="hamburger-box"> <div class="hamburger-inner"></div> </div> </button> </div> <?php perch_content('flex block'); ?> </div> </div> </div> </div> <footer> <?php perch_get_javascript(); ?> <script> // Google Analytics
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-3588451-2', 'auto');  // Replace with your property ID.
      ga('send', 'pageview'); </script> </footer> </body> </html>